// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jtpydtjgjnvzmjaynlal.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0cHlkdGpnam52em1qYXlubGFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxODIwMzMsImV4cCI6MjA3Mzc1ODAzM30.Vt0B9JFZV8gha-_w1kAJW8EIq7x-xFYyEDU1fDV6zQk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});